version: '3.8'

services:
  # 1. BASE DE DATOS
  db:
    image: postgres:17
    container_name: vesta_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: vesta_user
      POSTGRES_PASSWORD: vesta_password
      POSTGRES_DB: vesta_db
    ports:
      - "5433:5432"
    volumes:
      - vesta_pgdata:/var/lib/postgresql/data
    networks:
      - vesta_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vesta_user -d vesta_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. API BACKEND (Ahora s√≠, solo 2 contenedores como Sprintix)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vesta_api_container
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vesta_db
      SPRING_DATASOURCE_USERNAME: vesta_user
      SPRING_DATASOURCE_PASSWORD: vesta_password
      JWT_SECRET: "ClaveSecretaSuperSeguraParaVestaProyecto2024"
      JWT_EXPIRATION: 86400000
    networks:
      - vesta_net

# RED COMPARTIDA (Igual que Sprintix)
networks:
  vesta_net:
    name: vesta_network_shared
    driver: bridge

volumes:
  vesta_pgdata: